// File: constants/tracks.ts

export interface LyricLine {
  time: number; // Thời gian bắt đầu của dòng lyric (tính bằng giây)
  text: string;
}

export interface Track {
  id: string;
  url: any;
  title: string;
  artist: string;
  artwork: any;
  duration: number;
  lyrics?: LyricLine[];
  downloadUrl?: string;
  localUrl?: string;
  genre?: string;
}

// --- DỮ LIỆU LYRICS ---

const simpleLoveLyrics: LyricLine[] = [
    { time: 7.2, text: "Yeah-ee-yeah, yeah-ee-yeah, yeah-ee-yeah-ee-yeah" },
    { time: 13.0, text: "Uầy" },
    { time: 13.7, text: "Đưa chân dạo quanh nơi khắp phố xá bụi bay vào mắt, yah" },
    { time: 17.8, text: "Bụng reo đói mãi, anh tấp vào shop mua ly mì gói, yah" },
    { time: 21.5, text: "Đập vào đôi mắt anh muốn chới với, whoa, oh my god, whoa" },
    { time: 25.0, text: "Nàng tựa là ai xinh đến đắm đuối, không may thì ngất" },
    { time: 28.8, text: "Đứng chết im tức khắc, nàng nhẹ nhàng lướt qua" },
    { time: 32.5, text: "Tiếng sét ái tình đã đánh, xem như duyên chúng ta" },
    { time: 36.0, text: "Tay buông cả ly mì xuống, nhiều người nhìn quá đê" },
    { time: 39.5, text: "Anh không nói tiếng Hàn Quốc, nhưng biết nói saranghae" },
    { time: 43.0, text: "Lo đứng mộng mơ em đi đâu mất, yahh" },
    { time: 45.0, text: "I'm fall in love, yahh" },
    { time: 46.4, text: "Đôi chân chạy nhanh hết tất ngóc ngách, to find you girl, yahh" },
    { time: 50.3, text: "Em trôi thật mau giữa đám đông bon chen người qua, yahh" },
    { time: 53.8, text: "Anh mãi chạy theo sau bóng em dẫu xa thật xa, yahh" },
    { time: 57.3, text: "Lạc vào hình bóng nàng, nét tinh tươm xinh ghê, yah" },
    { time: 60.8, text: "Em tựa tiên chốn nào ghé sang qua nơi anh vậy" },
    { time: 64.5, text: "Môi ngây ngô đỏ mềm, khiến anh như tan ra, yah" },
    { time: 67.9, text: "Thôi thì đã lỡ rồi mình trót yêu luôn em nha, yahhh" },
    { time: 71.9, text: "Simple love, yah, simple love, yah" },
    { time: 75.4, text: "Simple love, simple love, oh simple love, yah" },
    { time: 79.2, text: "Ôi trên đấy giáng xuống thần tiên đi vào trong giấc mơ" },
    { time: 82.8, text: "Baby girl, I'm gonna say: \"You're the only one\"" },
    { time: 86.2, text: "Simple love, yah, simple love, yah" },
    { time: 89.8, text: "Simple love, simple love, oh simple love, yah" },
    { time: 93.3, text: "Rolling with me on the way, yo my candy girl" },
    { time: 96.9, text: "Saranghae, saranghae, simple love, girl" },
    { time: 101.1, text: "Bởi vì một phút ba mươi giây, nàng vút xa nơi đây, yeah" },
    { time: 104.5, text: "Đang nơi đâu, đi tìm hoài khắp nơi bao lâu, yeah" },
    { time: 108.0, text: "Thấy em đang ngồi trên ghế, ahh" },
    { time: 111.0, text: "Đôi Nike tinh tế, ahh" },
    { time: 112.5, text: "Ăn gì mà xinh thế, khiến anh quên luôn con đường về, yeah yeah" },
    { time: 117.7, text: "Lạc vào hình bóng nàng, nét tinh tươm xinh ghê, yah" },
    { time: 121.2, text: "Em tựa tiên chốn nào ghé sang qua nơi anh vậy" },
    { time: 124.7, text: "Môi ngây ngô đỏ mềm, khiến anh như tan ra, yah" },
    { time: 128.2, text: "Thôi thì đã lỡ rồi mình trót yêu luôn em nha, yahhh" },
    { time: 132.3, text: "Simple love, yah, simple love, yah" },
    { time: 135.8, text: "Simple love, simple love, oh simple love, yah" },
    { time: 139.5, text: "Ôi trên đấy giáng xuống thần tiên đi vào trong giấc mơ" },
    { time: 143.0, text: "Baby girl, I'm gonna say: \"You're the only one\"" },
    { time: 146.5, text: "Simple love, yah, simple love, yah" },
    { time: 150.0, text: "Simple love, simple love, oh simple love, yah" },
    { time: 153.5, text: "Rolling with me on the way, yo my candy girl" },
    { time: 157.0, text: "Saranghae, saranghae, simple love, girl" },
    { time: 160.9, text: "Anh ơi, nên dừng lại, dừng lại để thấy đôi chân em mỏi mệt" },
    { time: 164.4, text: "Em đang thôi miên anh bằng nụ cười thật duyên" },
    { time: 166.4, text: "Lạc vào đồng cỏ xanh, thiên đường hoa bướm ong bay lượn" },
    { time: 169.4, text: "Tia lửa mém cầu kì, thiên đường không còn, nên nàng rơi vào nơi trần gian sao" },
    { time: 173.1, text: "Anh thì kiên cường, mong rằng gánh em bao phần gian lao" },
    { time: 176.2, text: "Việc gì phải ôm buồn đau, riêng mình ta, riêng mình ta" },
    { time: 179.7, text: "Nụ cười nở muôn ngàn hoa, muôn ngàn hoa, muôn ngàn hoa" },
    { time: 183.3, text: "Simple love, yah, simple love, yah" },
    { time: 186.8, text: "Simple love, simple love, oh simple love, yah" },
    { time: 190.3, text: "Ôi trên đấy giáng xuống thần tiên đi vào trong giấc mơ" },
    { time: 193.8, text: "Baby girl, I'm gonna say: \"You're the only one\"" },
    { time: 197.3, text: "Simple love, yah, simple love, yah" },
    { time: 200.8, text: "Simple love, simple love, oh simple love, yah" },
    { time: 204.3, text: "Rolling with me on the way, yo my candy girl" },
    { time: 207.8, text: "Saranghae, saranghae, simple love, girl" },
    { time: 211.3, text: "Thứ em thấy ở TV show, chẳng có đâu, tình yêu nhiệm màu" },
    { time: 214.8, text: "Don't believe what people show off, yeah, they just wanna show off" },
    { time: 218.3, text: "Show off, show off, show off, show off, show off" },
    { time: 221.7, text: "I just need a simple love, girl" },
];

const loveLikeYouLyrics: LyricLine[] = [
    { time: 97.46, text: "I always thought I might be bad" },
    { time: 101.46, text: "Now I'm sure that it's true" },
    { time: 105.08, text: "'Cause I think you're so good" },
    { time: 109.18, text: "And I'm nothing like you" },
    { time: 112.24, text: "Look at you go" },
    { time: 114.11, text: "I just adore you" },
    { time: 116.84, text: "I wish that I knew" },
    { time: 120.10, text: "What makes you think I'm so special" },
    { time: 128.03, text: "If I could begin to do" },
    { time: 131.53, text: "Something that does right by you" },
    { time: 134.96, text: "I would do about anything" },
    { time: 137.65, text: "I would even learn how to love" },
    { time: 142.24, text: "When I see the way you look" },
    { time: 145.75, text: "Shaken by how long it took" },
    { time: 149.14, text: "I could do about anything" },
    { time: 151.90, text: "I could even learn how to love like" },
    { time: 158.91, text: "" },
    { time: 160.99, text: "You" },
    { time: 168.63, text: "You" },
    { time: 176.02, text: "You" },
    { time: 183.56, text: "You" },
];

const goldenLyrics: LyricLine[] = [
    { time: 16.05, text: "I was a ghost" },
    { time: 17.12, text: "I was alone, ha" },
    { time: 19.00, text: "어두워진 Ha" },
    { time: 21.07, text: "앞길 속에" },
    { time: 23.90, text: "Given the throne" },
    { time: 24.88, text: "I didn't know" },
    { time: 26.10, text: "How to believe" },
    { time: 28.03, text: "I was the queen that I'm meant to be" },
    { time: 30.79, text: "I lived two lives" },
    { time: 32.48, text: "Tried to play both sides" },
    { time: 34.61, text: "But I couldn't find my own place" },
    { time: 38.30, text: "Called a problem child" },
    { time: 40.32, text: "'Cause I got too wild" },
    { time: 42.51, text: "But now that's how I'm getting paid" },
    { time: 45.57, text: "끝없이 On stage" },
    { time: 46.78, text: "I'm done hiding, now I'm shining like I'm born to be" },
    { time: 54.12, text: "We dreamin' hard, we came so far, now I believe" },
    { time: 121.51, text: "We're goin' up, up, up" },
    { time: 123.78, text: "It's our moment" },
    { time: 125.38, text: "You know together we're glowing" },
    { time: 127.35, text: "Gonna be, gonna be golden" },
    { time: 129.25, text: "Oh, up, up, up" },
    { time: 131.58, text: "With our voices" },
    { time: 133.25, text: "영원히 깨질 수 없는" },
    { time: 135.16, text: "Gonna be, gonna be golden" },
    { time: 137.10, text: "Oh, I'm done hiding, now I'm shining like I'm born to be" },
    { time: 145.34, text: "Oh, our time, no fears, no lies, that's who we're born to be" },
    { time: 155.05, text: "Waited so long to break these walls down" },
    { time: 159.15, text: "To wake up and feel like me" },
    { time: 163.14, text: "Put these patterns all in the past now" },
    { time: 167.00, text: "And finally live like the girl they all see" },
    { time: 171.60, text: "No more hiding, I'll be shining like I'm born to be" },
    { time: 179.18, text: "'Cause we are hunters, voices strong, and I know I believe" },
    { time: 186.95, text: "We're goin' up, up, up" },
    { time: 189.27, text: "It's our moment" },
    { time: 190.90, text: "You know together we're glowing" },
    { time: 192.82, text: "Gonna be, gonna be golden" },
    { time: 194.72, text: "Oh, up, up, up" },
    { time: 197.10, text: "With our voices" },
    { time: 198.70, text: "영원히 깨질 수 없는" },
    { time: 200.64, text: "Gonna be, gonna be golden" },
    { time: 202.60, text: "Oh, I'm done hiding, now I'm shining like I'm born to be" },
    { time: 210.82, text: "Oh, our time, no fears, no lies, that's who we're born to be" },
    { time: 218.20, text: "You know we're" },
    { time: 219.18, text: "Gonna be, gonna be golden" },
    { time: 220.92, text: "We're gonna be, gonna be" },
    { time: 223.00, text: "Born to be, born to be glowin'" },
    { time: 224.91, text: "밝게 빛나는 우리" },
    { time: 226.32, text: "You know that it's our time, no fears, no lies, that's who we're born to be" },
];

const mindGamesLyrics: LyricLine[] = [
    { time: 3.12, text: "(I smell your fear, I smell your fear)" },
    { time: 20.39, text: "There's another side that you don't know, you don't know" },
    { time: 25.86, text: "I can't wait to get you all alone, all alone" },
    { time: 31.62, text: "Once I'm in there, ain't no letting go, letting go" },
    { time: 37.23, text: "Watch me turn your mind into my home" },
    { time: 42.85, text: "Ooh, ooh, ooh" },
    { time: 51.30, text: "Mind-mind games until you lose control" },
    { time: 55.01, text: "Ooh, ooh, ooh" },
    { time: 62.64, text: "(Mind-mind games, mind games, mind games)" },
    { time: 65.41, text: "Now that I'm in, there's no letting go" },
    { time: 67.94, text: "And your emptiness begins" },
    { time: 71.22, text: "Once I grip onto your mind and soul" },
    { time: 73.67, text: "Your brightness starts to dim" },
    { time: 76.81, text: "Sin after sin, you won't feel no more" },
    { time: 79.03, text: "And you've lost your trust again" },
    { time: 82.52, text: "I know you wish you could let me know" },
    { time: 84.73, text: "That you're praying for an end" },
    { time: 87.41, text: "I can lie to you and tell you you can get me out your head" },
    { time: 92.94, text: "But I'm lovin' all the pain I'm causing you too much instead, baby" },
    { time: 99.48, text: "There's another side that you don't know, you don't know" },
    { time: 105.00, text: "I can't wait to get you all alone, all alone" },
    { time: 110.68, text: "Once I'm in there, ain't no letting go, letting go" },
    { time: 116.38, text: "Watch me turn your mind into my home" },
    { time: 121.65, text: "Ooh, ooh, ooh" },
    { time: 130.24, text: "Mind-mind games until you lose control" },
    { time: 134.20, text: "Ooh, ooh, ooh" },
    { time: 141.64, text: "(Mind-mind games until you lose control)" },
    { time: 145.11, text: "Bitch, you think you know me" },
    { time: 146.69, text: "Holdin' back the dark force so long, call me Kenobi" },
    { time: 149.05, text: "Thinkin' I just gotta force this song when I get lonely" },
    { time: 152.02, text: "Take advantage, say you'll hold me close but never show me" },
    { time: 154.92, text: "Someone told me you can only disguise and be pretend" },
    { time: 157.84, text: "The tears manifest sometimes my only friend" },
    { time: 160.78, text: "You'll never see them again, they hide behind a mask" },
    { time: 163.54, text: "Thinkin' you're winnin' with all of your grinning but I got the last laugh" },
    { time: 166.38, text: "I can lie to you and tell you I can't get you out my head" },
    { time: 171.94, text: "But I'm lovin' watching you think you're controlling me instead, singin'" },
    { time: 178.34, text: "There's another side that you don't know, you don't know" },
    { time: 184.09, text: "I can't wait to get you all alone, all alone" },
    { time: 189.89, text: "Once I'm in there, ain't no letting go, letting go" },
    { time: 195.35, text: "Watch me turn your mind into my home (home, home)" },
    { time: 200.94, text: "Ooh, ooh, ooh" },
    { time: 209.21, text: "Mind-mind games until you lose control" },
    { time: 213.03, text: "Ooh, ooh, ooh" },
    { time: 220.66, text: "Mind-mind games until you lose control" },
    { time: 244.35, text: "Until you lose control" },
];

const nastyDogLyrics: LyricLine[] = [
    { time: 8.51, text: "Kitty cat, kitty cat, run, run, run" },
    { time: 14.46, text: "Kitty cat, kitty cat, run, run, run" },
    { time: 24.89, text: "Kitty cat, kitty cat, run, run, run" },
    { time: 26.97, text: "I'm the dog in the Benz with the big chrome gun" },
    { time: 28.69, text: "Looking for a coochie proper" },
    { time: 30.14, text: "Hot mama, big dog, big game, no drama" },
    { time: 32.60, text: "Never make babies, can't get rabies" },
    { time: 34.81, text: "Makin head hit and it's crazy" },
    { time: 36.79, text: "And when I catch a little kitty lookin oh so tough" },
    { time: 38.91, text: "Bring hot water cause I might get stuck" },
    { time: 41.02, text: "EW!, while I'ma stop in Cosmo" },
    { time: 42.90, text: "'Cause my lyrical content is gando" },
    { time: 44.63, text: "Stickin to the mind of the critics" },
    { time: 47.65, text: "I'm still with it, dogs gotta get it (hey come here buddy)" },
    { time: 49.30, text: "Bow wow was the sound of the hound with the see town crown" },
    { time: 51.42, text: "I sniff around 'til I pin cats down" },
    { time: 53.12, text: "They like to run up trees" },
    { time: 54.65, text: "But I can bring 'em back down with a jingle of my car keys" },
    { time: 57.62, text: "Most men is dogs and most dogs is nasty" },
    { time: 59.96, text: "I can't let a cat run past me" },
    { time: 61.50, text: "Watch your skirt when you're walking through the mall" },
    { time: 64.19, text: "'Cause I ain't nothin but a nasty dog" },
    { time: 69.95, text: "Dog" },
    { time: 72.49, text: "(I ain't nothin) but a nasty dog" },
    { time: 78.29, text: "(What kinda dog is this?)" },
    { time: 82.15, text: "(*Woman knocks on door*)" },
    { time: 84.04, text: "Woman #1: What you want?" },
    { time: 84.94, text: "Woman #2: Can Mix come out to play?" },
    { time: 86.14, text: "Woman #1: Nasty bitch" },
    { time: 86.84, text: "So I'm back putting black kitty cats on their backs" },
    { time: 88.58, text: "Big macks never lag, on wax I'ma low down dog" },
    { time: 91.54, text: "I just stepped up and other dogs want to flex up" },
    { time: 94.01, text: "I ain't tryna be the best rapper, just a big macker" },
    { time: 96.87, text: "So sit on down and watch the bank stacker" },
    { time: 98.82, text: "It still ain't easy G" },
    { time: 100.92, text: "But this dog's a Bentley" },
    { time: 102.44, text: "So I'ma chase that cat 'til I can't chase no mo'" },
    { time: 104.76, text: "There she goes in a drop top Rocko" },
    { time: 106.87, text: "What's up with your car sweetie?" },
    { time: 108.59, text: "Come on down and jump in the Black-ini" },
    { time: 110.78, text: "Another brother tryna diss and Mix ain't down" },
    { time: 113.02, text: "Oh no, hot sauce in my Dog Chow" },
    { time: 115.42, text: "Another brother can't see me" },
    { time: 116.48, text: "But he wants to be me" },
    { time: 117.58, text: "I'm laying these thangs on 'em freely" },
    { time: 119.00, text: "Now you got fo' fo' chromes, straight layin on your dome" },
    { time: 121.60, text: "And get your mangy ass on" },
    { time: 123.06, text: "Back to the kitty, cause she's kinda pretty" },
    { time: 125.03, text: "I can't stop lookin at her ti-ti-ti- face" },
    { time: 127.16, text: "Me and cat mama rolled into the distant fog" },
    { time: 129.92, text: "Little did she know I'm a nasty dog" },
    { time: 134.15, text: "(old, stinky, rotten, ripe and old dog)" },
    { time: 139.96, text: "I'm slingin that game like it ain't jack" },
    { time: 141.48, text: "She's fat, black cat but she won't look back" },
    { time: 143.37, text: "Rolling this Viper, tryna entice her" },
    { time: 145.77, text: "Don't need a front but I likes to" },
    { time: 147.48, text: "Get me an attitude, fightin over who pulls up" },
    { time: 150.16, text: "Two dogs in a sports car, playing old cuts" },
    { time: 152.32, text: "Turned down the James Brown" },
    { time: 153.61, text: "I said \"what's up girl\" but she still won't turn around" },
    { time: 156.15, text: "Attitude (what up), attitude (what's up)" },
    { time: 158.04, text: "When the girls are playing the role and what do we do?" },
    { time: 159.58, text: "(Call 'em stuck up)" },
    { time: 160.45, text: "Now we're both tryna front like we don't care" },
    { time: 162.20, text: "Whip a U-turn to get a quick stare" },
    { time: 164.72, text: "But the face was hurtin (damn)" },
    { time: 166.28, text: "The girl's grill was tore up, mustache wasn't working" },
    { time: 168.93, text: "Grandma old face with a nom ass body" },
    { time: 170.68, text: "\"Mack Daddy\" didn't want this hotty" },
    { time: 172.75, text: "Flashback to the crying game" },
    { time: 174.03, text: "I hate to see any parts of that poon-tang" },
    { time: 176.47, text: "Usually I'm quick to mack but that's road kill, back it up black" },
    { time: 180.57, text: "Quiz it, to giz it with the quick hiz its" },
    { time: 182.65, text: "For zeeze it, tazease it, it's hard for me to leave it" },
    { time: 184.56, text: "Not sexist, just sexy with my dia-logue" },
    { time: 187.96, text: "'Cause I'm a nasty" },
    { time: 189.65, text: "(Snapping and barking and biting)" },
    { time: 193.06, text: "Dog (snapping and barking and biting)" },
    { time: 198.42, text: "(Snapping and barking and biting)" },
    { time: 201.69, text: "(Snapping and barking and biting)" },
    { time: 205.03, text: "'Cause I'm a nasty dog" },
    { time: 209.05, text: "Yeah, dog" },
    { time: 213.14, text: "Nasty dog" },
    { time: 221.38, text: "Nasty dog" },
    { time: 229.43, text: "Nasty dog" },
    { time: 237.52, text: "Nasty dog" },
];

const loveForYouLyrics: LyricLine[] = [
    { time: 10.09, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 12.39, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 14.56, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 16.92, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 19.07, text: "I don't want to think" },
    { time: 21.46, text: "Nor do I wanna know" },
    { time: 23.81, text: "The reality of what I’m being told" },
    { time: 27.96, text: "Don't wanna waste your time" },
    { time: 30.25, text: "I know my wrongs aren't right" },
    { time: 32.28, text: "Can you just be mine?" },
    { time: 34.24, text: "You know you got me like" },
    { time: 36.40, text: "So emotional" },
    { time: 38.30, text: "You know I'm not able" },
    { time: 40.74, text: "To control my love for you" },
    { time: 45.17, text: "So emotional" },
    { time: 47.19, text: "You know I'm not able" },
    { time: 49.91, text: "To control" },
    { time: 52.13, text: "My love for you" },
    { time: 53.96, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 56.33, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 58.67, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 60.74, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 63.06, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 65.20, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 67.28, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 69.72, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 71.54, text: "Got so much love for you" },
    { time: 73.75, text: "Cuts through me in my heart" },
    { time: 75.87, text: "You know what you put me through" },
    { time: 78.12, text: "We can't just be apart" },
    { time: 80.18, text: "I just can’t seem to hide" },
    { time: 82.49, text: "You are my ride or die" },
    { time: 84.75, text: "I just got (I just got)" },
    { time: 86.69, text: "So much love for you" },
    { time: 88.83, text: "I don't wanna hear your lies" },
    { time: 90.33, text: "You know it’s love in a disguise" },
    { time: 92.30, text: "Our souls intertwined" },
    { time: 94.13, text: "You know, that’s damn right (you know)" },
    { time: 97.32, text: "You ain't gonna fess up" },
    { time: 98.85, text: "You ain't gonna tell me how I messed up" },
    { time: 101.00, text: "You ain't gonna tell me how to dress up" },
    { time: 103.25, text: "I ain't gonna wait for your touch" },
    { time: 106.51, text: "So untouchable" },
    { time: 108.73, text: "Yet not so capable" },
    { time: 111.25, text: "To control my love for you" },
    { time: 115.24, text: "So unattainable" },
    { time: 117.52, text: "I'm in a spiral" },
    { time: 119.98, text: "Making sure you know" },
    { time: 122.51, text: "My love for you" },
    { time: 124.44, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 126.69, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 128.91, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 131.12, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 133.26, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 135.49, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 137.54, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 139.83, text: "(Love for you, ooh-ah ooh-ah)" },
    { time: 141.99, text: "Love for you, ooh-ah" },
    { time: 144.41, text: "You got me so, so hooked up on you" },
    { time: 148.54, text: "I know you want me too" },
    { time: 150.93, text: "Love for you, ooh-ah" },
    { time: 152.99, text: "You know you got me so" },
    { time: 154.91, text: "Hooked up on you" },
    { time: 157.20, text: "I know you want me too" },
];

const obsessedLyrics: LyricLine[] = [
    { time: 6.99, text: "Why are you so obsessed with me?" },
    { time: 13.69, text: "All I wanna know" },
    { time: 22.24, text: "All up in the blogs saying we met at the bar" },
    { time: 24.17, text: "When I don't even know who you are" },
    { time: 26.03, text: "Saying we up in your house, saying I'm up in your car" },
    { time: 28.10, text: "But you in LA and I'm out at Jermaine's" },
    { time: 29.86, text: "I'm up in the A, you're so, so lame" },
    { time: 31.62, text: "And no one here even mentions your name" },
    { time: 33.71, text: "It must be the weed, it must be the E" },
    { time: 35.57, text: "'Cause you be popping heard, you get it popping" },
    { time: 37.71, text: "Why you so obsessed with me? Boy, I wanna know" },
    { time: 42.22, text: "Lying that you're sexing me when everybody knows" },
    { time: 46.28, text: "It's clear that you're upset with me" },
    { time: 48.27, text: "Finally found a girl that you couldn't impress" },
    { time: 51.18, text: "Last man on the Earth still couldn't get this" },
    { time: 52.98, text: "You're delusional, you're delusional" },
    { time: 54.71, text: "Boy, you're losing your mind" },
    { time: 56.28, text: "It's confusing you, you're confused you know" },
    { time: 58.44, text: "Why you wasting your time?" },
    { time: 60.02, text: "Got you all fired up with your Napoleon complex" },
    { time: 62.81, text: "Seeing right through you like you're bathing in Windex" },
    { time: 66.48, text: "Boy, why you so obsessed with me?" },
    { time: 77.16, text: "Obsessed, obsessed, obsessed" },
    { time: 82.07, text: "You on your job, you hating hard" },
    { time: 84.23, text: "Ain't gon' to feed you, I'ma let you starve" },
    { time: 86.10, text: "Grasping for air, I'm ventilation" },
    { time: 88.18, text: "You outta breath, hope you ain't waiting" },
    { time: 90.05, text: "Telling the world how much you miss me" },
    { time: 91.91, text: "But we never were, so why you tripping?" },
    { time: 93.80, text: "You a mom and pop, I'm a corporation" },
    { time: 95.46, text: "I'm the press conference, you a conversation" },
    { time: 97.61, text: "Why you so obsessed with me? And boy, I wanna know" },
    { time: 102.41, text: "Lying that you're sexing me when everybody knows" },
    { time: 106.36, text: "It's clear that you're upset with me" },
    { time: 108.31, text: "Finally found a girl that you couldn't impress" },
    { time: 111.35, text: "Last man on the Earth still couldn't get this" },
    { time: 112.97, text: "You're delusional, you're delusional" },
    { time: 114.80, text: "Boy, you're losing your mind" },
    { time: 116.05, text: "It's confusing you, you're confused you know" },
    { time: 119.00, text: "Why you wasting your time?" },
    { time: 120.29, text: "Got you all fired up with your Napoleon complex" },
    { time: 122.41, text: "Seeing right through you like you're bathing in Windex" },
    { time: 126.59, text: "Boy, why you so obsessed with me?" },
    { time: 137.01, text: "Obsessed, obsessed, obsessed" },
    { time: 142.04, text: "Why you so obsessed with me?" },
    { time: 151.27, text: "Why you so obsessed with me? Boy, I wanna know" },
    { time: 155.05, text: "Lying that you're sexing me when everybody knows" },
    { time: 158.74, text: "It's clear that you're upset with me" },
    { time: 160.08, text: "Finally found a girl that you couldn't impress" },
    { time: 163.81, text: "Last man on the earth still couldn't get" },
    { time: 165.66, text: "Why you so obsessed with me? Boy, I wanna know" },
    { time: 170.50, text: "Lying that you're sexing me when everybody knows" },
    { time: 173.76, text: "It's clear that you're upset with me" },
    { time: 176.98, text: "Finally found a girl that you couldn't impress" },
    { time: 178.30, text: "Last man on the Earth still couldn't get this" },
    { time: 179.32, text: "Why you so obsessed with me?" },
    { time: 189.44, text: "Obsessed, obsessed, obsessed" },
    { time: 194.41, text: "Why you so obsessed with me?" },
];

// --- DANH SÁCH BÀI HÁT CHÍNH ---

export const TRACKS: Track[] = [
  {
    id: '1',
    url: require('../assets/audio/track1.mp3'),
    title: 'Nắng ấm xa dần',
    artist: 'Sơn Tùng M-TP',
    artwork: require('../assets/images/cover1.jpg'),
    duration: 255,
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    genre: 'Pop',
  },
  {
    id: '2',
    url: require('../assets/audio/track2.mp3'),
    title: 'Em của ngày hôm qua',
    artist: 'Sơn Tùng M-TP',
    artwork: require('../assets/images/cover2.jpg'),
    duration: 224,
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    genre: 'Pop',
  },
  {
    id: '3',
    url: require('../assets/audio/track3.mp3'),
    title: 'Simple Love',
    artist: 'Obito & Seachains & Davis',
    artwork: require('../assets/images/cover3.jpg'),
    duration: 231,
    lyrics: simpleLoveLyrics,
    genre: 'Rap',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  },
  {
    id: '4',
    url: require('../assets/audio/track4.wav'),
    title: 'WAV SONG',
    artist: 'Gia Huy',
    artwork: require('../assets/images/cover4.jpg'),
    duration: 231,
    genre: 'Rap',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  },
  {
    id: '5',
    url: require('../assets/audio/Love like you.mp3'),
    title: 'Love Like You',
    artist: 'Rebecca Sugar',
    artwork: require('../assets/images/cover5.jpg'),
    duration: 191,
    lyrics: loveLikeYouLyrics,
    genre: 'Soundtrack',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  },
  {
    id: '6',
    url: require('../assets/audio/Golden.mp3'),
    title: 'Golden',
    artist: 'HUNTRX, EJAE, AUDREY NUNA, REI AMI',
    artwork: require('../assets/images/cover6.jpg'),
    duration: 194,
    lyrics: goldenLyrics,
    genre: 'K-Pop',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  },
  {
    id: '7',
    url: require('../assets/audio/mindgames.mp3'),
    title: 'Mind Games',
    artist: 'Sickick',
    artwork: require('../assets/images/cover7.jpg'),
    duration: 258,
    lyrics: mindGamesLyrics,
    genre: 'Electronic',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
  },
  {
    id: '8',
    url: require('../assets/audio/nastydog.mp3'),
    title: 'Nasty Dog',
    artist: 'Sir Mix-A-Lot',
    artwork: require('../assets/images/cover8.jpg'),
    duration: 240,
    lyrics: nastyDogLyrics,
    genre: 'Hip-Hop',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
  },
  {
    id: '9',
    url: require('../assets/audio/loveforyou.mp3'),
    title: 'Love for You',
    artist: 'LOVELI LORI, ovg!',
    artwork: require('../assets/images/cover9.jpg'),
    duration: 160,
    lyrics: loveForYouLyrics,
    genre: 'Pop',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
  },
  {
    id: '10',
    url: require('../assets/audio/obsessed.mp3'),
    title: 'Obsessed',
    artist: 'Mariah Carey',
    artwork: require('../assets/images/cover10.jpg'),
    duration: 200,
    lyrics: obsessedLyrics,
    genre: 'R&B',
    downloadUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
  },
];